require "Items/ProceduralDistributions"
-- YJRubberduckyBlack
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyBlack");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyBlack");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyBlack");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyBlue
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyBlue");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyBlue");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyBlue");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyBrown
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyBrown");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyBrown");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyBrown");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyGreen
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyGreen");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyGreen");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyGreen");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyPink
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyPink");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyPink");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyPink");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyPurple
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyPurple");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyPurple");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyPurple");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyRed
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyRed");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyRed");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyRed");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyTeal
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyTeal");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyTeal");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyTeal");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyWhite
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyWhite");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyWhite");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyWhite");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);
-- YJRubberduckyYellow
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.YJRubberduckyYellow");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Base.YJRubberduckyYellow");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.YJRubberduckyYellow");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3);