require "Items/ProceduralDistributions"
-- 92jeepYJWinch2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.92jeepYJWinch2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.92jeepYJWinch2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- 92jeepYJSnorkel2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.92jeepYJSnorkel2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.92jeepYJSnorkel2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
-- Base.92jeepYJMagazine
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Base.92jeepYJMagazine");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Base.92jeepYJMagazine");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 0.3);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Base.92jeepYJMagazine");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "Base.92jeepYJMagazine");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Base.92jeepYJMagazine");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 0.2);